# Generated by Django 4.2.2 on 2023-08-06 03:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import online_store.tools.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The brand name must be a minimum of 2 chars')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The category name must be a minimum of 2 chars')]),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.category',),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The attribute name must be a minimum of 2 chars')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2, message='The product name must be a minimum of 2 chars')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='Product price cannot be negative or zero')]),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The attribute name must be a minimum of 2 chars')]),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The attribute value must be a minimum of 1 chars')]),
        ),
    ]
