# Generated by Django 4.2.2 on 2023-08-07 09:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import online_store.tools.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_brand_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The category name must be a minimum of 2 chars'), online_store.tools.custom_validators.validate_category_not_self]),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.category'),
        ),
    ]
