# Generated by Django 4.2.2 on 2023-08-07 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_name_alter_category_parent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='The category name must be a minimum of 2 chars')]),
        ),
    ]
