# Generated by Django 4.2.2 on 2023-07-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='products',
            new_name='product',
        ),
    ]
