# Generated by Django 4.2.2 on 2023-07-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='items',
        ),
        migrations.AddField(
            model_name='inventory',
            name='deliveries',
            field=models.ManyToManyField(related_name='items', to='inventory.delivery'),
        ),
    ]
