# Generated by Django 4.2.2 on 2023-08-07 08:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import online_store.tools.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_delivery_options_alter_inventory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='deliveries',
        ),
        migrations.AddField(
            model_name='inventory',
            name='delivery',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.RESTRICT, to='inventory.delivery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1, message='Cost cannot be negative or zero ')]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, validators=[online_store.tools.custom_validators.validate_characters_digits_dashes_only]),
        ),
    ]
