# Generated by Django 4.2.2 on 2023-08-07 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_inventory_deliveries_inventory_delivery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1, message='Cost cannot be negative or zero ')]),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='invoice_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
