# Generated by Django 4.2.2 on 2023-08-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceData',
        ),
    ]
