# Generated by Django 4.2.2 on 2023-08-06 03:28

import django.core.validators
from django.db import migrations, models
import online_store.tools.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_invoicedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, validators=[online_store.tools.custom_validators.validate_characters_digits_only]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=60, validators=[online_store.tools.custom_validators.validate_characters_only]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=56, validators=[django.core.validators.MinLengthValidator(4, message='There is no country with less than 4 characters'), online_store.tools.custom_validators.validate_characters_only]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[online_store.tools.custom_validators.validate_numbers_plus_sign_only]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=60, validators=[online_store.tools.custom_validators.validate_characters_only]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='First name cannot have less than 2 characters'), online_store.tools.custom_validators.validate_characters_only]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='Last name cannot have less than 2 characters'), online_store.tools.custom_validators.validate_characters_only]),
        ),
    ]
